package com.inz.z.note_book.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.inz.z.note_book.bean.NoteGroup;
import com.inz.z.note_book.bean.NoteGroupWithInfo;
import com.inz.z.note_book.bean.NoteInfo;

import com.inz.z.note_book.database.NoteGroupDao;
import com.inz.z.note_book.database.NoteGroupWithInfoDao;
import com.inz.z.note_book.database.NoteInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteGroupDaoConfig;
    private final DaoConfig noteGroupWithInfoDaoConfig;
    private final DaoConfig noteInfoDaoConfig;

    private final NoteGroupDao noteGroupDao;
    private final NoteGroupWithInfoDao noteGroupWithInfoDao;
    private final NoteInfoDao noteInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteGroupDaoConfig = daoConfigMap.get(NoteGroupDao.class).clone();
        noteGroupDaoConfig.initIdentityScope(type);

        noteGroupWithInfoDaoConfig = daoConfigMap.get(NoteGroupWithInfoDao.class).clone();
        noteGroupWithInfoDaoConfig.initIdentityScope(type);

        noteInfoDaoConfig = daoConfigMap.get(NoteInfoDao.class).clone();
        noteInfoDaoConfig.initIdentityScope(type);

        noteGroupDao = new NoteGroupDao(noteGroupDaoConfig, this);
        noteGroupWithInfoDao = new NoteGroupWithInfoDao(noteGroupWithInfoDaoConfig, this);
        noteInfoDao = new NoteInfoDao(noteInfoDaoConfig, this);

        registerDao(NoteGroup.class, noteGroupDao);
        registerDao(NoteGroupWithInfo.class, noteGroupWithInfoDao);
        registerDao(NoteInfo.class, noteInfoDao);
    }
    
    public void clear() {
        noteGroupDaoConfig.clearIdentityScope();
        noteGroupWithInfoDaoConfig.clearIdentityScope();
        noteInfoDaoConfig.clearIdentityScope();
    }

    public NoteGroupDao getNoteGroupDao() {
        return noteGroupDao;
    }

    public NoteGroupWithInfoDao getNoteGroupWithInfoDao() {
        return noteGroupWithInfoDao;
    }

    public NoteInfoDao getNoteInfoDao() {
        return noteInfoDao;
    }

}
