package com.inz.z.music.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.inz.z.music.database.ChooseInterestDb;
import com.inz.z.music.database.ItemSongsBean;
import com.inz.z.music.database.SongsFolderBean;
import com.inz.z.music.database.SongsImageBean;

import com.inz.z.music.database.ChooseInterestDbDao;
import com.inz.z.music.database.ItemSongsBeanDao;
import com.inz.z.music.database.SongsFolderBeanDao;
import com.inz.z.music.database.SongsImageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chooseInterestDbDaoConfig;
    private final DaoConfig itemSongsBeanDaoConfig;
    private final DaoConfig songsFolderBeanDaoConfig;
    private final DaoConfig songsImageBeanDaoConfig;

    private final ChooseInterestDbDao chooseInterestDbDao;
    private final ItemSongsBeanDao itemSongsBeanDao;
    private final SongsFolderBeanDao songsFolderBeanDao;
    private final SongsImageBeanDao songsImageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chooseInterestDbDaoConfig = daoConfigMap.get(ChooseInterestDbDao.class).clone();
        chooseInterestDbDaoConfig.initIdentityScope(type);

        itemSongsBeanDaoConfig = daoConfigMap.get(ItemSongsBeanDao.class).clone();
        itemSongsBeanDaoConfig.initIdentityScope(type);

        songsFolderBeanDaoConfig = daoConfigMap.get(SongsFolderBeanDao.class).clone();
        songsFolderBeanDaoConfig.initIdentityScope(type);

        songsImageBeanDaoConfig = daoConfigMap.get(SongsImageBeanDao.class).clone();
        songsImageBeanDaoConfig.initIdentityScope(type);

        chooseInterestDbDao = new ChooseInterestDbDao(chooseInterestDbDaoConfig, this);
        itemSongsBeanDao = new ItemSongsBeanDao(itemSongsBeanDaoConfig, this);
        songsFolderBeanDao = new SongsFolderBeanDao(songsFolderBeanDaoConfig, this);
        songsImageBeanDao = new SongsImageBeanDao(songsImageBeanDaoConfig, this);

        registerDao(ChooseInterestDb.class, chooseInterestDbDao);
        registerDao(ItemSongsBean.class, itemSongsBeanDao);
        registerDao(SongsFolderBean.class, songsFolderBeanDao);
        registerDao(SongsImageBean.class, songsImageBeanDao);
    }
    
    public void clear() {
        chooseInterestDbDaoConfig.clearIdentityScope();
        itemSongsBeanDaoConfig.clearIdentityScope();
        songsFolderBeanDaoConfig.clearIdentityScope();
        songsImageBeanDaoConfig.clearIdentityScope();
    }

    public ChooseInterestDbDao getChooseInterestDbDao() {
        return chooseInterestDbDao;
    }

    public ItemSongsBeanDao getItemSongsBeanDao() {
        return itemSongsBeanDao;
    }

    public SongsFolderBeanDao getSongsFolderBeanDao() {
        return songsFolderBeanDao;
    }

    public SongsImageBeanDao getSongsImageBeanDao() {
        return songsImageBeanDao;
    }

}
