package com.inz.z.music.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.inz.z.music.database.ChooseInterestDb;

import com.inz.z.music.database.ChooseInterestDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chooseInterestDbDaoConfig;

    private final ChooseInterestDbDao chooseInterestDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chooseInterestDbDaoConfig = daoConfigMap.get(ChooseInterestDbDao.class).clone();
        chooseInterestDbDaoConfig.initIdentityScope(type);

        chooseInterestDbDao = new ChooseInterestDbDao(chooseInterestDbDaoConfig, this);

        registerDao(ChooseInterestDb.class, chooseInterestDbDao);
    }
    
    public void clear() {
        chooseInterestDbDaoConfig.clearIdentityScope();
    }

    public ChooseInterestDbDao getChooseInterestDbDao() {
        return chooseInterestDbDao;
    }

}
